version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - mongo
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1

  mongo:
    image: mongo:6.0.4
    ports:
      - "27018:27017"
    networks:
      - backend
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    driver: local

networks:
  backend:
    name: backend
