version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - mongo
    env_file:
      - .env.dev
    volumes:
      - type: bind
        source: .
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules
    deploy:
      mode: replicated
      replicas: 1

  mongo:
    image: mongo:6.0.4
    ports:
      - "27018:27017"
    networks:
      - backend
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    driver: local

networks:
  backend:
    name: backend
