version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1

  mongo:
    image: mongo:6.0.4
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    driver: local
