# Overlay configuration to enable debuggers
version: "3"
services:
  app:
    command:
      - "npm"
      - "run"
      - "debug-docker"
    ports:
      - "5000:5000"
      # inspect debug port
      - "9229:9229"
