# Use the official Node.js  LTS image
FROM node:20.10.0-bullseye-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory (better layer caching)
COPY package*.json ./

# Install dependencies
RUN --mount=type=cache,target=/usr/src/app/.npm \
  npm set cache /usr/src/app/.npm && \
  npm install

# Copy all local files to the working directory
COPY . .

# Command to run the app
CMD ["npm", "run", "dev"]
