version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - postgres_db
    env_file:
      - .env.local
    volumes:
      - type: bind
        source: .
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules
    deploy:
      mode: replicated
      replicas: 1

  postgres_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
    ports:
      - "6543:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    driver: local

networks:
  backend:
    name: backend
